`Sprockets::Asset` no longer responds to `#body`
Change to using `#to_s`

Fixes the following error:

```
Failure/Error: expect('application.css').to respect_selector_limit
     NoMethodError:
       undefined method `body' for #<Sprockets::Asset:0x007f8769463c08>
```